FROM ultralytics/ultralytics:latest
WORKDIR /app
RUN apt-get update && apt-get install --no-install-recommends -y ffmpeg
ENV PATH="/usr/bin:${PATH}"
RUN pip install --no-cache-dir gradio yt_dlp
COPY yolo_classes.json .
COPY utils.py app.py gradio_env .
EXPOSE 7860
CMD ["python3", "app.py"]