apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker/compose.run.cpu.yml convert -o k8s/ --deployment
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: gradio-app
  name: gradio-app
spec:
  type: NodePort
  ports:
    - name: "7860"
      port: 7860
      targetPort: 7860
      nodePort: 30007
  sessionAffinity: ClientIP
  selector:
    io.kompose.service: gradio-app
